# Generated by Django 3.2.15 on 2022-10-21 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20221021_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Publicación de servicio aprobada'),
        ),
    ]
