# Generated by Django 3.2.15 on 2022-10-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20221021_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_mod',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
