# Generated by Django 3.2.15 on 2022-10-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_mod',
            field=models.DateField(auto_now=True, verbose_name='Ultima Actualización'),
        ),
        migrations.AlterField(
            model_name='service',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Publicación aprobada'),
        ),
    ]
