# Generated by Django 3.2.15 on 2022-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20221022_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
