# Generated by Django 3.2.15 on 2022-10-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20221022_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='office_hours',
            field=models.TextField(blank=True, null=True, verbose_name='Horario de Atención'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Descripcion de servicios ofrecidos', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='Imagen de Portada', upload_to='media/services', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Red Social')),
                ('url', models.URLField(verbose_name='URL de la Red Social')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Servicio')),
            ],
        ),
    ]
