# Generated by Django 3.2.15 on 2022-10-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20221022_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='service',
            name='phone1',
            field=models.CharField(blank=True, help_text=541234567890, max_length=12, null=True, verbose_name='Telefono 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='phone2',
            field=models.CharField(blank=True, help_text=541234567890, max_length=12, null=True, verbose_name='Telefono 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp',
            field=models.CharField(blank=True, help_text=541234567890, max_length=12, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Red Social'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
