# Generated by Django 3.2.15 on 2022-10-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_paymentmethods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='paymethod',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Visa'), ('3', 'Mastercard'), ('4', 'Mercado Pago')], max_length=2, verbose_name='Metodo de Pago'),
        ),
    ]
