# Generated by Django 3.2.15 on 2022-10-25 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0013_auto_20221024_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
