# Generated by Django 3.2.15 on 2022-10-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_price'),
        ('services', '0015_alter_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.timediscount', verbose_name='Cuota'),
        ),
        migrations.AlterField(
            model_name='service',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan', verbose_name='Plan'),
        ),
    ]
