# Generated by Django 3.2.15 on 2022-10-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20221025_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen de Portada', null=True, upload_to='media/services', verbose_name='Imagen'),
        ),
    ]
