# Generated by Django 3.2.15 on 2022-10-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/icons_paymethods', verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='paymethod',
            field=models.CharField(max_length=50, verbose_name='Metodo de Pago'),
        ),
    ]
