# Generated by Django 3.2.15 on 2022-10-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20221027_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='icon',
        ),
    ]
