# Generated by Django 3.2.15 on 2022-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_remove_paymentmethods_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
    ]
