# Generated by Django 3.2.15 on 2022-10-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('type_doc', models.CharField(choices=[('D', 'Cedula'), ('P', 'Pasaporte'), ('R', 'RNC')], default='D', max_length=1, verbose_name='Tipo de Documento')),
                ('n_doc', models.CharField(max_length=100, verbose_name='Documento')),
                ('date_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('type_user', models.CharField(choices=[('1', 'Super Usuario'), ('2', 'Empleado'), ('3', 'Cliente')], default='3', max_length=1, verbose_name='Tipo de Usuario')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica que el usuario pertenece al staff de SERVIFLIX', verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, help_text='Indica que el usuario esta activo en la plataforma', verbose_name='Usuario Activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
