# Generated by Django 3.2.15 on 2022-10-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_create',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_doc',
            field=models.CharField(choices=[('D', 'DNI'), ('P', 'Pasaporte'), ('R', 'RNC')], default='D', max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
