# Generated by Django 3.2.15 on 2022-10-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='n_doc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_doc',
            field=models.CharField(blank=True, choices=[('D', 'DNI'), ('P', 'Pasaporte'), ('R', 'RNC')], default='D', max_length=1, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
