# Generated by Django 3.2.15 on 2022-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221028_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_doc',
            field=models.CharField(blank=True, choices=[('D', 'DNI'), ('P', 'Pasaporte'), ('R', 'RNC')], max_length=1, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
