# Generated by Django 3.2.15 on 2022-10-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='timediscount',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='timediscount',
            name='descuento',
        ),
        migrations.AddField(
            model_name='timediscount',
            name='discount_rate',
            field=models.FloatField(default=0, help_text='(%)', verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='timediscount',
            name='time',
            field=models.CharField(help_text='Tiempo a pagar', max_length=50, verbose_name='Tiempo'),
        ),
    ]
